### ISSUE TITLE
Support mybatis-plus

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-mybatis#100]
Following #95 and we consider to support [mybatis-plus](https://github.com/baomidou/mybatis-plus) in this repo.

**Comment by zhfeng** [comment]
@zohar-soul I just creat mybati-plus module and feel free to work on the extension. I will invite you to join the maintain team.

**Comment by zhfeng** [comment]
@zohar-soul Do you get any update on this issue and please raise a PR for initial codes. We can get more discuss.

**Comment by zohar-soul** [comment]
> @zohar-soul Do you get any update on this issue and please raise a PR for initial codes. We can get more discuss.

I will submit a minimum available version at the weekend, which can be discussed at that time

**Comment by zhfeng** [comment]
Thanks @zohar-soul and I create https://github.com/quarkiverse/quarkus-mybatis/pull/122 to add mybatis-plus support.
