### ISSUE TITLE
xml configure problem

### ISSUE THREAD

**Issue by liuzhaozhao** [quarkiverse/quarkus-mybatis#108]
Inject failed when I used xml to configure Mapper，Can you help me look at this problem

xml :
`
<configuration>
    <environments default="development">
        <environment id="development">
            <transactionManager type="JDBC"/>
            <dataSource type="QUARKUS">
            </dataSource>
        </environment>
    </environments>
    <mappers>
        <mapper resource="mapper/TaskMapper.xml"/>
    </mappers>
</configuration>
`

code:

@Inject
TaskMapper taskMapper;

**Comment by zhfeng** [comment]
@liuzhaozhao So what is the problem ? taksMapper is null ?

**Comment by zhfeng** [comment]
I close this issue sine there is further information and I think it could be similar to #114. @liuzhaozhao feel free to reopen it if you still get a problem when upgrading to use the lastest one.
