### ISSUE TITLE
Will this extension work with quarkus 2.0 ?

### ISSUE THREAD

**Issue by rpdeadly** [quarkiverse/quarkus-mybatis#113]
Hi quarkus-mybatis team.  I'm a huge fan of mybatis and quarkus and wanted to know if the team had plans to port the code to quarkus 2.0.

**Comment by rpdeadly** [comment]
closing question after reviewing pull request. Looks like it will work.

**Comment by zhfeng** [comment]
Thanks @rpdeadly and I can confirm that we support Quarkus 2.x
