### ISSUE TITLE
How to add MybatisPlusInterceptor

### ISSUE THREAD

**Issue by 362228416** [quarkiverse/quarkus-mybatis#137]
How to add MybatisPlusInterceptor?

**Comment by 362228416** [comment]
```java
@ApplicationScoped
@Startup
public class BeanConfig {

    @Produces
    public MybatisPlusInterceptor optimisticLockerInterceptor() {
        System.out.println("===aaa===");
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new OptimisticLockerInnerInterceptor());
        return interceptor;
    }

}
```
Console print ===aaa===, but when update show err msg
### Error updating database.  Cause: org.apache.ibatis.binding.BindingException: Parameter 'MP_OPTLOCK_VERSION_ORIGINAL' not found. Available parameters are [param1, et]

**Comment by zhfeng** [comment]
We introduce a new propery ```quarkus.mybatis-plus.pagination.enabled``` in #172
