### ISSUE TITLE
Get the dataSource from the Container

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-mybatis#139]
Currently we are using Datasouces.from(name) to get the dataSource by Agroal. It needs to change to use ArcContainer to get the data source while some other extension (such sharding-sphere-jdbc ) could produce the dataSource in different way. So it should be get them from the quarkus container.

**Comment by naah69** [comment]
is there any progress?
we used dynamic data source to load datebase config.so we need this feature.

**Comment by zhfeng** [comment]
No, not yet. Is it possible to share a simple usecase of your application ? I'm thinking to get the DataSource from the ArcContainer at runtime but it needs more investigation.

**Comment by naah69** [comment]
i had reslove my problem ,i  just need `quarkus.datasource.db-kind` in config file,the others in dynamic config

**Comment by zhfeng** [comment]
I'm glad to hear this message. And did you create the ```DataSource``` dynamicly by yourself but not use ```quarkus-agroal``` extension ?

**Comment by naah69** [comment]
i still use `quarkus-agroal`,without other dependency

**Comment by zhfeng** [comment]
OK, I see and it looks like you create a ```other``` type of ```db-kind``` and implement the configs by yourself ?

**Comment by zhfeng** [comment]
I'd like to close it sinec this is not a common way in the quarkus. We need to keep to depend on `quarkus-agroal` to create DataSource.
