### ISSUE TITLE
Doc url wrong

### ISSUE THREAD

**Issue by fsantagada-goo** [quarkiverse/quarkus-mybatis#14]
No a true issue but link (https://quarkus.io/guides/mybatis) to doc is wrong.
Please fix.

**Comment by gsmet** [comment]
@zhfeng we have an Antora setup for the Quarkiverse.

You can mimic what I did here: https://github.com/quarkiverse/quarkiverse-github-app/tree/master/docs .

And then add your repo here: https://github.com/quarkiverse/quarkiverse-docs/blob/master/antora-playbook.yml

**Comment by zhfeng** [comment]
Thanks @gsmet and I will take a look

**Comment by zhfeng** [comment]
@gsmet I raise https://github.com/quarkiverse/quarkiverse-docs/pull/4 to add the Quarkus MyBatis documentation. Also I'd merged  https://github.com/quarkiverse/quarkus-mybatis/pull/30 to add the docs and antora.yml. Can you take a look at them ? I'm not sure if it needs to do a new release for these changes ? or just have them in the repo ?
