### ISSUE TITLE
Are there plans to support Mybatis SQL Mapper XML functionality?

### ISSUE THREAD

**Issue by Xinmudotmoe** [quarkiverse/quarkus-mybatis#145]
This is a feature that Mybatis comes with and is used very frequently in slightly larger projects.

I did some kind of available state by modifying the quarkus-mybatis source code, but unfortunately I don't have the development experience of quarkus. Merging it may not be appropriate.

Related documentation: 

[https://mybatis.org/mybatis-3/configuration.html#mappers](https://mybatis.org/mybatis-3/configuration.html#mappers)

 [https://mybatis.org/mybatis-3/sqlmap-xml.html](https://mybatis.org/mybatis-3/sqlmap-xml.html)

**Comment by zhfeng** [comment]
I think we has supported for xml configuration but I'm not sure the sqlmap is working. So can you provide a simple test or project for using the Sql Mapper XML ? I'd  like to take a look at it. Thanks a lot !

**Comment by Xinmudotmoe** [comment]
> I think we has supported for xml configuration but I'm not sure the sqlmap is working. So can you provide a simple test or project for using the Sql Mapper XML ? I'd like to take a look at it. Thanks a lot !

I may find the problem, I found that **org.apache.ibatis.session.Configuration** has been created **two**, the former lacks SQL Mapper Xml information. I am trying to organize a minimal test item to reproduce the problem.

**Comment by Xinmudotmoe** [comment]
@zhfeng Through the breakpoint of **org.apache.ibatis.session.configuration**.addMappedStatement (line: 768), I found two different **Configuration**, which happen to be Controller's acquisition of a Configuration without XML. Maybe that's the point.

It could also be that my error caused the xml configuration to not work properly.

Simple test project: [https://github.com/Xinmudotmoe/quarkus_mybatis_sql_mapper_example](https://github.com/Xinmudotmoe/quarkus_mybatis_sql_mapper_example)

**Comment by zhfeng** [comment]
Thanks @Xinmudotmoe and I think this is similar with https://github.com/quarkiverse/quarkus-mybatis/issues/114

And current there is a workaround to add ```@MapperDataSource("xmlconfig")``` to specify using the xm configuration. I just make some changes with your example to make sure it works. Please check https://github.com/Xinmudotmoe/quarkus_mybatis_sql_mapper_example/pull/1

I will raise another issue to improve the xml configuration.

**Comment by zhfeng** [comment]
And feel free to close this issue if you get your example work properly. Thanks again !

**Comment by Xinmudotmoe** [comment]
@zhfeng  It's working. Thanks.
