### ISSUE TITLE
@Select annotation backfill. If the query field is not consistent with the entity field, it will not be backfilled. I don't know whether it can be optimized

### ISSUE THREAD

**Issue by MrYang-Jia** [quarkiverse/quarkus-mybatis#205]
Using the @select annotation, it is found that the select field part must be consistent with the field name of the entity in order to backfill normally. I don't know whether there is any means to define it. In this way, when subqueries are performed, the entity field can be backfilled with select * or select database fields

使用 @Select 注解，发现 select 字段部分必须跟 实体的 字段名一致才能正常回填，不知道是否有什么手段可以定义，这样子查询的时候，就可以使用 select * 或 select 数据库字段 回填实体字段

Define table City object
定义表 City  对象
```
@Data
@TableName("city")
public class City implements Serializable {
    @TableField(value = "city_id")
    private String cityId;
    @TableField(value = "city_name")
    private String cityName;
    @TableField(value = "region_id")
    private Integer regionId;

```
Define CityMapper
定义 CityMapper

```
@Mapper
@MapperDataSource("<default>")
public interface CityMapper extends BaseMapper<City> {

    // Cityname can be backfilled normally, city_ ID cannot be backfilled to cityid
    // cityName 可以正常回填, city_id 无法回填到 cityId
    @Select("SELECT city_name cityName,city_id FROM city WHERE region_id = #{id} limit 1")
    City getCity(Integer id); // <1>
}

```
Define XML mapper mapping file
定义xml Mapper映射文件

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.edb.qarkus.demo.mapper.CityMapper">
    <resultMap id="BaseResultMap" type="com.edb.qarkus.demo.mapper.City">
        <id column="city_id" jdbcType="CHAR" property="cityId" />
        <result column="city_name" jdbcType="VARCHAR" property="cityName" />
        <result column="region_id" jdbcType="INTEGER" property="regionId" />
    </resultMap>
    <select id="findById" parameterType="int" resultMap="BaseResultMap">
        select * from city where region_id=#{id} limit 1
    </select>
</mapper>
```

When we call citymapper When getcity (1), you will find city Cityname has value, but city Cityid is not assigned, because there is no field name converted to cityid during select query, but I don't know if this is a bug? Or does it have to be set like this
If you can, I hope to provide a way to obtain field mapping from XML (normally, it already exists in the XML file of mabytis, and it should be able to backfill normally) or an annotation method of field mapping to achieve the effect of field consistency

当我们调用 CityMapper.getCity(1) 时，会发现 City.cityName 有值，但是 City.cityId 没有赋值，原因是 select 查询的时候，没有转换成cityId 的字段名，但我并不知道这个是不是bug? 还是说必须这么设置
可以的话，希望可以提供一个从xml获取字段映射（正常来说mabytis的xml文件里已经有了，应该能正常回填才对） 或 提供一个字段映射的注解方式，达到字段一致的效果

**Comment by zohar-soul** [comment]
You can try adding mapUnderscoreToCamelCase to mybatis settings.xml

see https://mybatis.org/mybatis-3/configuration.html

**Comment by MrYang-Jia** [comment]
> You can try adding mapUnderscoreToCamelCase to mybatis settings.xml
> 
> see https://mybatis.org/mybatis-3/configuration.html#settings

Thank you, but the result is still not backfilled. I have set it

![image](https://user-images.githubusercontent.com/76804829/176983409-c6445898-c9be-4ad9-83f2-3ed910a4fcd1.png)

**Comment by zhfeng** [comment]
Well, I think we can not mix using of `xml configuration` and `annotation`. So it could be useful to add `@ResutlMap` in `CityMapper`? did you use `quarkus-mybatis` or `quarkus-mybatis-plus`?

**Comment by MrYang-Jia** [comment]
> Well, I think we can not mix using of `xml configuration` and `annotation`. So it could be useful to add `@ResutlMap` in `CityMapper`? did you use `quarkus-mybatis` or `quarkus-mybatis-plus`?

是的，我两个都用了，所以我也挺困惑的
Yes, I used both of them, so I was confused

**Comment by MrYang-Jia** [comment]
后面我是用 (In the back, I use)
@TableName(value= "e_regulation", autoResultMap = true)
public class EReg extends BaseEntity
然后用(Then use)
@ResultMap("mybatis-plus_EReg")
The problem has been solved, so in the initial stage, it may be really mixed up to solve the problem, and some friends may encounter it. I don't know if this is the correct answer, but this is the way to solve the problem
解决了问题，所以初期可能还真得这么混用解决问题，可能还会有小伙伴碰到，我不知道我这个算不是正确答案，但是目前就是这么解决了问题
