### ISSUE TITLE
Cannot use cursors in quarkus-mybatis

### ISSUE THREAD

**Issue by p91paul** [quarkiverse/quarkus-mybatis#239]
Using cursors with annotation-based transactions leads to java.lang.IllegalStateException: A Cursor is already closed.

After very complicated debugging, this seems to happen because quarkus-mybatis opens a new session for each query instead of relying on a managed session that should be opened when the jta transaction starts.

The SqlSessionManager.SqlSessionInterceptor detects no localSqlSession and opens an autoSqlSession that gets closed just after the mapper method returns, which leads to immediately closing the cursor

![image](https://user-images.githubusercontent.com/2157006/204043020-6a8b75c4-a6db-4356-8ee9-5fc3cca06313.png)

Attached a project reproducing the issue (I used oracle but I suppose it's db independent), see com.example.resource.GreetingResource#greetings
[transactions.zip](https://github.com/quarkiverse/quarkus-mybatis/files/10094722/transactions.zip)

**Comment by p91paul** [comment]
As a workaround, I used the following code, explicitly getting a session factory. However, I would expect transaction management to work for cursors as well, like in spring mybatis integration.

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/greetings")
    @Transactional(rollbackOn = Exception.class)
    public List<String> greetings() throws Exception {
        log.debug("greetings");
        List<String> x = new ArrayList<>();
        GreetingMapper mapper;
        try (SqlSession sqlSession = sqlSessionFactory.openSession()) {
            mapper = sqlSession.getMapper(GreetingMapper.class);
            try (Cursor<String> select = mapper.select()) {
                for (String s : select) {
                    x.add(s);
                    System.out.println(s);
                }
            }
        }
        log.debug("greetings done");
        return x;
    }

**Comment by zhfeng** [comment]
Thanks @p91paul for reporting and very handy re-producer project. I will take a look these days.

**Comment by zhfeng** [comment]
It seems that we need to provide a similar QuarkusSessionManager to manage a SqlSession in the transactions.

**Comment by zhfeng** [comment]
@p91paul I just wonder to know if `Cursor` is only expected to work in a transaction?

**Comment by p91paul** [comment]
Not necessarily in a transaction, the important thing is that the cursor is opened and used without closing the session. Using Transactional is just a handy way of declaratively defining the session boundaries that works in Spring Boot.
