### ISSUE TITLE
Prepare for Quarkus 3.x

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-mybatis#243]
Refer to https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x#upgrade

**Comment by zhfeng** [comment]
Now we use `prepare-quarkus-3.x` branch to do some upgrading works.

**Comment by ppalaga** [comment]
Any progress/ETA @zhfeng ?

**Comment by zhfeng** [comment]
I had test `prepare-quarkus-3-x` and it looks good. I will update the `main` branch to quarkus 3 then prepare for a new release. That will happen in next days.
