### ISSUE TITLE
使用quarkus-mybatisplus多数据源找不到自定义方法

### ISSUE THREAD

**Issue by zuochangqin** [quarkiverse/quarkus-mybatis#251]

**Comment by zhfeng** [comment]
I think it needs to define `quarkus.mybatis.mapper-locations` property to have all of the folders which contains mapper xml files and they should be seperated by `,`.

Also in the mapper xml file, you have to use `namespace` attribute and refer to the class which shoud  have the annotaion `@MapperDataSource` with the right value of the datasource. see the example in https://github.com/quarkiverse/quarkus-mybatis/blob/master/mybatis/integration-tests/src/main/resources/otherMapper/BookMapper.xml#L3
