### ISSUE TITLE
使用mybatis-plus meta-object-handler 问题

### ISSUE THREAD

**Issue by wangyi12358** [quarkiverse/quarkus-mybatis#262]
您好，我尝试在项目中使用meta-object-handler，但是在进行配置 INSERT UPDATE的时候却不生效，我不知道是什么原因，下面是我的代码

![image](https://user-images.githubusercontent.com/39055759/219260817-239b5344-f7f0-4938-baa8-9ad0f544c12b.png)
![image](https://user-images.githubusercontent.com/39055759/219260900-52b12a9a-9462-43a1-80a1-63d73e6e8555.png)
![image](https://user-images.githubusercontent.com/39055759/219260950-08eca7bc-dcce-49ed-aa94-5cf3d59cf766.png)

在我进行update的时候，MetaHandler updateFill 都没执行，我现在找不到到底是什么问题了

**Comment by zhfeng** [comment]
It looks like you are using 'kotlin` and I think we have never test it with `quarkus-mybatis`. So it coudl be very helpful if you can provide a reproducer for this issue?

Is `MetaObjectHandler` working with Java?

**Comment by wangyi12358** [comment]
> 
嗯嗯好的

**Comment by wangyi12358** [comment]
> It looks like you are using `kotlin` and I think we have never test it with `quarkus-mybatis`. So it could be very helpful if you can provide a reproducer for this issue?
> 
> Is `MetaObjectHandler` working with Java?

嗯嗯好的

**Comment by wangyi12358** [comment]
> It looks like you are using `kotlin` and I think we have never test it with `quarkus-mybatis`. So it could be very helpful if you can provide a reproducer for this issue?
> 
> Is `MetaObjectHandler` working with Java?

https://github.com/wangyi12358/quarkus-mybatis-plus-demo
您好，这是仓库地址
sql目录是mysql表配置
您需要在config/application.yml 修改数据库配置
通过./mvnw compile quarkus:dev 启动
访问 http://localhost:8888/hello 就会复现我上面说的问题 在我insert的时候 我的create_time update_time 并没有被赋值

**Comment by zhfeng** [comment]
Thanks for your demo! I will take a look.

And even if I can read Chinese, it could help more people understand the issue when we describe it in English.

**Comment by wangyi12358** [comment]
> Thanks for your demo! I will take a look.
> 
> And even if I can read Chinese, it could help more people understand the issue when we describe it in English.

Okay, thanks you

**Comment by zhfeng** [comment]
Hi @wangyi12358 

It seems that we do not support this propery right now. I just check https://github.com/quarkiverse/quarkus-mybatis/blob/73e4d83bd573a82e752f85de70f5d07ad4c046aa/mybatis-plus/runtime/src/main/java/io/quarkiverse/mybatis/plus/MyBatisPlusConfig.java#L7-L15

Do you have any detail for this configuration in mybatis-plus? I can take a look to see if we can add it .

**Comment by wangyi12358** [comment]
> Hi @wangyi12358
> 
> It seems that we do not support this propery right now. I just check
> 
> https://github.com/quarkiverse/quarkus-mybatis/blob/73e4d83bd573a82e752f85de70f5d07ad4c046aa/mybatis-plus/runtime/src/main/java/io/quarkiverse/mybatis/plus/MyBatisPlusConfig.java#L7-L15
> 
> Do you have any detail for this configuration in mybatis-plus? I can take a look to see if we can add it .

I filled it with reference to the configuration of [com.baomidou mybatis-plus](https://mybatis.plus/config/#metaobjecthandler).
It seems that it is not supported.
So what should I do when I want to fill in a value during insert or update.

**Comment by zhfeng** [comment]
@wangyi12358 I'm working on this issue and we can add a config to support this feature.

**Comment by zhfeng** [comment]
Please try it with `1.0.7`

**Comment by wangyi12358** [comment]
> Please try it with `1.0.7`

Okay, thank you
