### ISSUE TITLE
Support for custom SqlInjector

### ISSUE THREAD

**Issue by zuochangqin** [quarkiverse/quarkus-mybatis#289]
I want to use InsertBatchSomeColumn, Please add Support for custom SqlInjector.
As follows in springboot:
public class EasySqlInjector extends DefaultSqlInjector {

	@Override
	public List<AbstractMethod> getMethodList(Class<?> mapperClass, TableInfo tableInfo) {
		List<AbstractMethod> methodList = super.getMethodList(mapperClass, tableInfo);
		methodList.add(new InsertBatchSomeColumn()); // 添加InsertBatchSomeColumn方法
		return methodList;
	}

}

GlobalConfig globalConfig = new GlobalConfig();
    globalConfig.setSqlInjector(new EasySqlInjector());

**Comment by zhfeng** [comment]
Is it possible to provide a unit test for `EasySqlInjector`?

**Comment by zuochangqin** [comment]
[quarkus-mybatisplus-sqlinjector.zip](https://github.com/quarkiverse/quarkus-mybatis/files/11175677/quarkus-mybatisplus-sqlinjector.zip)

Get the demo project up and running and execute the following request.
`curl --location --request POST 'http://localhost:8888/mybatis/users' \
--header 'Content-Type: application/json' \
--data-raw '[{"id":1,"name":"zhangsan1"},{"id":2,"name":"zhangsan2"},{"id":3,"name":"zhangsan3"}]'`

**Comment by zhfeng** [comment]
@zuochangqin Thanks for providing a example project but I can not find  `EasySqlInjector` in it. Is there anything I missed?
I'm sorry that I am not familiar with `mybatis-plus`. Can you explain more details about how `EasySqlInjector` is working?

**Comment by zuochangqin** [comment]
My current question is how to inject the customized EasySqlInjector into GlobalConfig, which currently lacks configuration.

**Comment by zuochangqin** [comment]
My current question is how to inject the customized EasySqlInjector into GlobalConfig, which currently lacks configuration

**Comment by zhfeng** [comment]
I can add a configuration for add `SqlInjector` but I still want to know how it could impact the SQL and write a test to verify it.

**Comment by zuochangqin** [comment]
The EasySqlInjector code is as follows

public class EasySqlInjector extends DefaultSqlInjector {

	@Override
	public List<AbstractMethod> getMethodList(Class<?> mapperClass, TableInfo tableInfo) {
		List<AbstractMethod> methodList = super.getMethodList(mapperClass, tableInfo);
		methodList.add(new InsertBatchSomeColumn()); // 添加InsertBatchSomeColumn方法
		return methodList;
	}

}

**Comment by zuochangqin** [comment]
Inject EasySqlInjector into GlobalConfig, tune the interface, and if multiple pieces of data can be inserted normally, it will be effective.

**Comment by zhfeng** [comment]
What is `InsertBatchSomeColumn` ? I can not find it in your project. 
So if `EasySqlInjector` is enabled, we can insert a batch of data?

**Comment by zuochangqin** [comment]
InsertBatchSomeColumn is in this jar package.
```
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
            <version>3.4.3.4</version>
        </dependency>
```

**Comment by zhfeng** [comment]
OK, I get it. Thanks for sharing with it!

**Comment by zhfeng** [comment]
@zuochangqin Please take a review of above changes!
