### ISSUE TITLE
java 1.8 run error

### ISSUE THREAD

**Issue by lbj2049** [quarkiverse/quarkus-mybatis#53]
support java 1.8

**Comment by zhfeng** [comment]
Can you show the detail of this error ? also I think Quarkus has deprecated Java 8 support since 1.4

**Comment by gsmet** [comment]
Quarkus 2.0 will require a minimum version of Java 11 so I would recommend that you update your JDK to 11.

@zhfeng while we deprecated JDK 8, we still support it for now so if it doesn't cost you, you could reintroduce JDK 8 support for a while. But that's really your call depending on how much work it is for you.

**Comment by zhfeng** [comment]
I just create https://github.com/quarkiverse/quarkus-mybatis/pull/88/files and if CI works. I think it should be OK to get the JDK8 support again.

**Comment by zhfeng** [comment]
@lbj2049 @Alujixixi I think this fix has been included in 0.0.8 relesae and can you check it please ?

**Comment by zhfeng** [comment]
@lbj2049 @Alujixixi since we upgrade to Quarkus 2.0.0.Final, I just consider to remove the JDK 8 support in the next new release maybe in 0.1.0
