### ISSUE TITLE
Support MyBatis XML configuration

### ISSUE THREAD

**Issue by caobingsheng** [quarkiverse/quarkus-mybatis#9]

**Comment by zhfeng** [comment]
Not yet. As I'm not a expert of MyBatis and also not simliar with the xml configuration, can you provide some deatails or maybe a simple example of it ?

Thanks a lot.

**Comment by caobingsheng** [comment]
Sql is written in xml file, for [example](https://mybatis.org/mybatis-3/zh/sqlmap-xml.html)

**Comment by zhfeng** [comment]
Thanks @caobingsheng and it is very helpful ! I will check it.
