### ISSUE TITLE
有计划支持mybatis plus 或者 basemapper 之类的嘛

### ISSUE THREAD

**Issue by zohar-soul** [quarkiverse/quarkus-mybatis#95]
没有单表crud 写业务着实有点累

**Comment by zhfeng** [comment]
I'm open to add these features. Can you provide some examples of mybatis plus or baseMapper ? Or something you are using to write the business logic ?

Thanks !

**Comment by zohar-soul** [comment]
https://github.com/abel533/Mapper
示例可以参见这里: https://github.com/abel533/Mybatis-Spring
感谢

**Comment by zhfeng** [comment]
Well, I just take a look at this Common Mapper and it seems an enhencement of MyBatis and providing more build-in methods in Mapper interface. So I think it could be better to introduce a new extension to support these features and this new extension can depend on ```quarkus-mybatis```.

**Comment by zhfeng** [comment]
Well, I just take a look at this Common Mapper and it seems an enhencement of MyBatis and providing more build-in methods in Mapper interface. So I think it could be better to introduce a new extension to support these features and this new extension can depend on ```quarkus-mybatis```.

**Comment by zohar-soul** [comment]
嗯, 建立一个新的扩展也是不错的想法

**Comment by zhfeng** [comment]
@zohar-soul Would you like to maintain this new extension under quarkiverse just like (quarkiverse/quarkus-mybatis-plus or another name if you like) ? I'm happy to help you to create it.

Thanks !

**Comment by zohar-soul** [comment]
> @zohar-soul您是否想在 quarkiverse 下维护这个新扩展，就像 (quarkiverse/quarkus-mybatis-plus 或其他名称，如果您愿意)？我很乐意帮助您创建它。
> 
> 谢谢 ！

我有这方面的想法, 我目前在quarkus-mybatis的基础上尝试做了些修改, 跑起来了一个初步的版本.

**Comment by zhfeng** [comment]
@zohar-soul That's great !

@gastaldi Is it possible for us to create a new repo for quarkiverse/quarkus-mybatis-plus ? and I think @zohar-soul had some initial works and  also he would like to maintain it.

**Comment by zohar-soul** [comment]
> @zohar-soul That's great !
> 
> @gastaldi Is it possible for us to create a new repo for quarkiverse/quarkus-mybatis-plus ? and I think @zohar-soul had some initial works and also he would like to maintain it.

方便的话可以给我一下你的联系方式(qq,微信之类的), 有需要的时候好请教你

**Comment by zhfeng** [comment]
@zohar-soul you are free to ask any question here in public way. I think you can get more help in this way since there are more guys in the community. Anyway, you can contact me by wechat (fzh_eng) if you like.

**Comment by zohar-soul** [comment]
> @zohar-soul你可以在这里公开提出任何问题。我认为您可以通过这种方式获得更多帮助，因为社区中有更多人。无论如何，如果您愿意，可以通过微信（fzh_eng）与我联系。

ok thanks

**Comment by gastaldi** [comment]
> @zohar-soul That's great !
> 
> @gastaldi Is it possible for us to create a new repo for quarkiverse/quarkus-mybatis-plus ? and I think @zohar-soul had some initial works and also he would like to maintain it.

Sure, no problem. Repository created in https://github.com/quarkiverse/quarkus-mybatis-plus

I assume it is an extension for this library: https://github.com/baomidou/mybatis-plus?

**Comment by zhfeng** [comment]
Thanks @gastaldi and I think you are right. It will be an extension for https://github.com/baomidou/mybatis-plus.

I will do an initial commit to setup https://github.com/quarkiverse/quarkus-mybatis-plus. And I wonder it is possible to add @zohar-soul as a Maintainer in the quarkus-mybatis-plus repo ?

**Comment by gastaldi** [comment]
I have already added @zohar-soul to the list of maintainers (an invitation link to join the @quarkiverse/quarkiverse-mybatis-plus team should have been sent for now - let me know if you received it @zohar-soul).

**Comment by zohar-soul** [comment]
@gastaldi @zhfeng 
I have received the invitation.
But what I'm trying to create extension is https://github.com/abel533/Mapper ,not https://github.com/baomidou/mybatis-plus. yet the principles of the two repo are similar
--------
我已经收到了邀请. 
但是我目前尝试支持的是之前我提到的这个 https://github.com/abel533/Mapper, 而不是 https://github.com/baomidou/mybatis-plus 
不过两个的原理是类似的

**Comment by gastaldi** [comment]
Ah so perhaps we should name it `quarkus-mybatis-mapper` instead, or maybe put it in another directory in the `quarkus-mybatis` repository (so they stay in sync between releases) 

WDYT @zhfeng @zohar-soul ?

**Comment by zhfeng** [comment]
@gastaldi @zohar-soul I'd suggest that we support mybatis-plus since it is much more activities in the community. And for https://github.com/abel533/Mapper, I think it's more like a personal project.

**Comment by zohar-soul** [comment]
> @gastaldi @zohar-soul I'd suggest that we support mybatis-plus since it is much more activities in the community. And for https://github.com/abel533/Mapper, I think it's more like a personal project.

ok, I will try to support mybatis-plus

**Comment by gastaldi** [comment]
@zhfeng WDYT about maintaining it in the same `quarkus-mybatis` repository under a subdirectory?

**Comment by zhfeng** [comment]
@gastaldi Well, that could be an option. So we can construct the directory like

```
├── mybatis/
├── mybatis-plus/
├── README.md
└── pom.xml
```
I'm not sure how this could affect the github workflow or anythin else. I will try to do this in the next week.

**Comment by gastaldi** [comment]
Yes, the GitHub workflow won't be affected since it would still be a multimodule project
